import Pond from '../assets/imgs/planets/pond.png';
import City from '../assets/imgs/planets/city.png';
import Cake from '../assets/imgs/planets/cake.png';
import Cube from '../assets/imgs/planets/cube.png';
import Rock from '../assets/imgs/planets/rock.png';
import Bread from '../assets/imgs/planets/bread.png';
import Earth from '../assets/imgs/planets/earth.png';
import Waterfall from '../assets/imgs/planets/waterfall.png';
import Fairy from '../assets/imgs/planets/fairy.png';
import Star from '../assets/imgs/planets/star.png';
import Mountain from '../assets/imgs/planets/mountain.png';
import Diamond from '../assets/imgs/planets/diamond.png';

export const planetDataList = new Map<string, string>();
planetDataList.set('0', Pond.src);
planetDataList.set('1', City.src);
planetDataList.set('2', Cake.src);
planetDataList.set('3', Cube.src);
planetDataList.set('4', Rock.src);
planetDataList.set('5', Bread.src);
planetDataList.set('6', Earth.src);
planetDataList.set('7', Waterfall.src);
planetDataList.set('8', Fairy.src);
planetDataList.set('9', Star.src);
planetDataList.set('10', Mountain.src);
planetDataList.set('11', Diamond.src);
