/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Gunther (https://sketchfab.com/xisoka45)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/apple-tree-low-poly-3d-model-956713eaab454decb4081fa38dfdb84b
title: Apple tree Low-poly 3D model
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { Object3D } from 'three';

type GLTFResult = GLTF & {
  nodes: {
    AppleTree_MaterialAppleTree001_0: THREE.Mesh;
    AppleTree_MaterialApple001_0: THREE.Mesh;
  };
  materials: {
    ['MaterialAppleTree.001']: THREE.MeshStandardMaterial;
    ['MaterialApple.001']: THREE.MeshStandardMaterial;
  };
};

export function AppleTreeModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/apple_tree/apple_tree.glb'
  ) as GLTFResult;
  return (
    <object3D>
      <group {...props} dispose={null}>
        <group
          position={[14.38, 0, -1.6]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group
              position={[407.62, 590.39, -100.55]}
              rotation={[1.89, 0.88, -2.05]}
              scale={100}
            >
              <group rotation={[Math.PI / 2, 0, 0]} />
            </group>
            <group
              position={[1082.42, 315.84, 488.34]}
              rotation={[Math.PI, 0.39, 3.04]}
              scale={100}
            />
            <group rotation={[-Math.PI / 2, 0, -0.36]} scale={90.44}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.AppleTree_MaterialAppleTree001_0.geometry}
                material={materials['MaterialAppleTree.001']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.AppleTree_MaterialApple001_0.geometry}
                material={materials['MaterialApple.001']}
              />
            </group>
          </group>
        </group>
      </group>
    </object3D>
  );
}

useGLTF.preload('/apple_tree/apple_tree.glb');
